import React from 'react'
import { compareAsc } from 'date-fns'
import { useActivitiesState, useActivitiesActions } from 'core/context'
import { generateFinishedActivities } from '../utils'
import { AcceptButton } from 'modules/activities/lib'
import { ActivityComplete } from './ActivityComplete'

export const HistoryList = () => {
  const { activities } = useActivitiesState()
  const { setActivities } = useActivitiesActions()
  const [numberRange, setNumberRange] = React.useState(0)
  const activitiesFinished = activities.filter(item => item.isFinished).sort((a, b) => compareAsc(a.dateFinished, b.dateFinished))

  const addFinishedActivities = () => {
    const newAutogeneratedItems = generateFinishedActivities(numberRange)
    const totalItems = [...activities, ...newAutogeneratedItems]

    setActivities(totalItems)
    setNumberRange(value => value + 1)
  }

  return (
    <div>
      <div className="flex justify-between">
        <div>Historial</div>
        <AcceptButton onClick={addFinishedActivities}>Generar 10 actividades</AcceptButton>
      </div>

      {activitiesFinished.map(item => (
        <ActivityComplete key={item.id} item={item} />
      ))}
    </div>
  )
}
