import React from 'react'
import { makeStyles } from '@material-ui/core'
import { useActivitiesState, useActivitiesActions } from 'core/context'
import { generateFinishedActivities } from '../utils'
import { Button } from 'modules/activities/lib'

const useStyles = makeStyles(theme => ({
  root: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    marginTop: 8,
    [theme.breakpoints.up('sm')]: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 0,
      marginBottom: 20,
    },
  },
  results: {
    color: theme.palette.primary.main,
    fontWeight: 600,
    fontSize: 14,
    [theme.breakpoints.up('sm')]: {
      fontSize: 16,
    },
  },
  button: {
    color: '#FFF',
    margin: '12px 0',
    [theme.breakpoints.up('sm')]: {
      width: 200,
      margin: 0,
      marginLeft: 12,
    },
  },
}))

export const TopContentHistotyList = ({ activitiesFinished = [] }) => {
  const classes = useStyles()
  const { activities } = useActivitiesState()
  const { setActivities } = useActivitiesActions()
  const [numberRange, setNumberRange] = React.useState(0)

  const addFinishedActivities = () => {
    const newAutogeneratedItems = generateFinishedActivities(numberRange)
    const totalItems = [...activities, ...newAutogeneratedItems]

    setActivities(totalItems)
    setNumberRange(value => value + 1)
  }

  return (
    <div className={classes.root}>
      <div className={classes.results}>{activitiesFinished.length} Resultado(s)</div>
      <Button onClick={addFinishedActivities} className={classes.button} variant="contained" color="primary">
        Generar 10 tareas
      </Button>
    </div>
  )
}
